services:
  geoip-service:
    image: retrogeo:latest
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./config:/app/config:rw
      - ./data:/app/data:rw      
    environment:
      - APP_ENV=production
      - MASTER_KEY_FILE=/app/config/.master.key

  geoip-worker:
    image: retrogeo:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MODE=WORKER
    entrypoint: ["python", "app/core/worker.py"]